### ISSUE TITLE
GC Overhead Limit Exception Generating the data (SF=30)

### ISSUE THREAD

**Issue by MohamedRagabAnas** [ldbc/ldbc_snb_datagen_spark#108]
I have the a problem with generation the data of SF=30, I am  facing the same problem with GC  overhead limit exceeded !

* mapred-site.xml
```
    <property>
        <name>mapreduce.map.memory.mb</name>
        <value>8192</value>
    </property>

    <property>
        <name>mapreduce.reduce.memory.mb</name>
        <value>12288</value>
    </property>

    <property>
        <name>mapreduce.map.java.opts</name>
        <value>-Xmx6144m -XX:-UseGCOverheadLimit</value>
    </property>

    <property>
        <name>mapreduce.reduce.java.opts</name>
        <value>-Xmx9216?m -XX:-UseGCOverheadLimit</value>
    </property>

   <property>
   <name>mapreduce.reduce.shuffle.memory.limit.percent</name>
  <value>0.06</value>
```

* yarn-site.xml

```
    <property>
        <name>yarn.nodemanager.resource.memory-mb</name>
        <value>100000</value>
    </property>

    <property>
        <name>yarn.scheduler.minimum-allocation-mb</name>
        <value>2048</value>
    </property>
```

```
19/10/29 20:32:02 INFO mapred.LocalJobRunner: reduce > reduce
19/10/29 20:32:02 INFO mapreduce.Job:  map 100% reduce 68%
Starting generation of block: 0
19/10/29 20:32:05 INFO mapred.LocalJobRunner: Generating activity of person 0 of block0 > reduce
19/10/29 20:32:08 INFO mapred.LocalJobRunner: Generating activity of person 0 of block0 > reduce
19/10/29 20:32:43 INFO mapred.LocalJobRunner: Generating activity of person 1000 of block0 > reduce
19/10/29 20:33:30 INFO mapred.LocalJobRunner: Generating activity of person 2000 of block0 > reduce
19/10/29 20:35:19 INFO mapred.LocalJobRunner: Generating activity of person 3000 of block0 > reduce
19/10/29 20:37:14 INFO mapred.LocalJobRunner: Generating activity of person 4000 of block0 > reduce
19/10/29 20:41:37 INFO mapred.LocalJobRunner: Generating activity of person 5000 of block0 > reduce
Cleaning up
19/10/29 20:56:10 INFO mapred.LocalJobRunner: reduce task executor complete.
19/10/29 20:56:11 WARN mapred.LocalJobRunner: job_local659389043_0017
java.lang.Exception: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:462)
        at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:529)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
```

Thanks in advance for your help

**Comment by szarnyasg** [comment]
@MohamedRagabAnas did you find a way to work around this issue?

**Comment by MohamedRagabAnas** [comment]
@szarnyasg  yeah Gabour, Thanks to your reply, I tired with the 'HADOOP_CLIENT_OPTS' environment variable, and it worked for me

**Comment by szarnyasg** [comment]
Great, glad it worked! See issue #4 for future reference.
