### ISSUE TITLE
Re-throw/display underlying error messages

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/ldbc_snb_datagen_spark#118]
Currently, the framework throws a `java.lang.Exception` with the actual exception hidden. It should provide more informative messages.

**Comment by szarnyasg** [comment]
The simplest solution I found was to set up a logger and set its log level `WARN`. This is what the commit above prints when executed on a code that (intentionally) does a division by zero:

```console
************************************************
* Starting: Person generation                  *
************************************************
2020-02-11 12:57:03 WARN  MetricsConfig:134 - Cannot locate configuration: tried hadoop-metrics2-jobtracker.properties,hadoop-metrics2.properties
2020-02-11 12:57:03 WARN  JobResourceUploader:149 - Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
2020-02-11 12:57:03 WARN  JobResourceUploader:482 - No job jar file set.  User classes may not be found. See Job or Job#setJar(String).
2020-02-11 12:57:04 WARN  LocalJobRunner:590 - job_local1486075935_0001
java.lang.Exception: java.lang.ArithmeticException: / by zero
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:492)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:552)
Caused by: java.lang.ArithmeticException: / by zero
	at ldbc.snb.datagen.hadoop.generator.HadoopPersonGenerator$HadoopPersonGeneratorMapper.map(HadoopPersonGenerator.java:70)
	at ldbc.snb.datagen.hadoop.generator.HadoopPersonGenerator$HadoopPersonGeneratorMapper.map(HadoopPersonGenerator.java:64)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:799)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:347)
	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:271)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Error during execution
null
Exception in thread "main" java.lang.Exception
	at ldbc.snb.datagen.hadoop.generator.HadoopPersonGenerator.run(HadoopPersonGenerator.java:174)
	at ldbc.snb.datagen.LdbcDatagen.personGenerateJob(LdbcDatagen.java:101)
	at ldbc.snb.datagen.LdbcDatagen.runGenerateJob(LdbcDatagen.java:256)
	at ldbc.snb.datagen.LdbcDatagen.main(LdbcDatagen.java:360)
```

**Comment by szarnyasg** [comment]
For the record, this is what you get now if you run out of memory:

```console
************************************************
* Starting: Person generation                  *
************************************************
2020-02-11 23:54:02,936 WARN mapreduce.JobResourceUploader: Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
2020-02-11 23:54:04,490 WARN mapred.LocalJobRunner: job_local282624368_0001
java.lang.Exception: java.lang.OutOfMemoryError: Java heap space
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:492)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:552)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.apache.hadoop.mapred.MapTask$MapOutputBuffer.init(MapTask.java:1000)
	at org.apache.hadoop.mapred.MapTask.createSortingCollector(MapTask.java:408)
	at org.apache.hadoop.mapred.MapTask.access$100(MapTask.java:82)
	at org.apache.hadoop.mapred.MapTask$NewOutputCollector.<init>(MapTask.java:710)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:782)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:347)
	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:271)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Error during execution
null
Exception in thread "main" java.lang.Exception
	at ldbc.snb.datagen.hadoop.generator.HadoopPersonGenerator.run(HadoopPersonGenerator.java:174)
	at ldbc.snb.datagen.LdbcDatagen.personGenerateJob(LdbcDatagen.java:101)
	at ldbc.snb.datagen.LdbcDatagen.runGenerateJob(LdbcDatagen.java:256)
	at ldbc.snb.datagen.LdbcDatagen.main(LdbcDatagen.java:360)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:323)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:236)
```
