### ISSUE TITLE
Cannot run program "python" (in directory "."): error=2

### ISSUE THREAD

**Issue by francast95** [ldbc/ldbc_snb_datagen_spark#135]
Hi I have a problem with python directory because the terminal delivery following code: 

************************************************
* Serializing static graph  *
************************************************
44 total seconds
Person generation time: 5
University correlated edge generation time: 4
Interest correlated edge generation time: 4
Random correlated edge generation time: 4
Edges merge time: 2
Person serialization time: 4
Person activity generation and serialization time: 12
Sorting update streams time: 5
Invariant schema serialization time: 0
Total Execution time: 44
Running Parameter Generation
Generating Interactive Parameters
Error during execution
Cannot run program "python" (in directory "."): error=2, No existe el archivo o el directorio
Exception in thread "main" java.io.IOException: Cannot run program "python" (in directory "."): error=2, No existe el archivo o el directorio
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at ldbc.snb.datagen.LdbcDatagen.runGenerateJob(LdbcDatagen.java:302)
	at ldbc.snb.datagen.LdbcDatagen.main(LdbcDatagen.java:347)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:323)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:236)
Caused by: java.io.IOException: error=2, No existe el archivo o el directorio
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 9 more
I have to set the environment variables how to 

JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
HADOOP_HOME=/home/fco/hadoop-3.2.1
LDBC_SNB_DATAGEN_HOME=/home/fco/ldbc_snb_datagen-0.3.2

and when i insert which python3 command delivery this /usr/bin/python3

I just need to solve that, this is for my work title please. @ArnauPrat @szarnyasg

**Comment by szarnyasg** [comment]
@francast95 Datagen requires Python 2. This is no longer part of major distributions so you need to install it with e.g. `sudo apt install python` (Ubuntu).

**Comment by francast95** [comment]
@szarnyasg yes I know but I have tried with python 2, 2.7, 3 and 3.6. Python 2 is in the same ways /usr/bin/python2 but I will try today and I tell you

**Comment by szarnyasg** [comment]
You can also simply set the binary of the Python runtime using `ldbc.snb.datagen.parametergenerator.python`. For example, you could add

```console
ldbc.snb.datagen.parametergenerator.python:python2
```

I've never tried this but it might do the trick on your system.

**Comment by francast95** [comment]
@szarnyasg I worked with jdbc 0.3.2 openjdk 11, maven 3.6.1 and python 2.7.16 and it gives me the following:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:11 min
[INFO] Finished at: 2020-04-18T21:25:39-04:00
[INFO] ------------------------------------------------------------------------
Warning: $HADOOP_HOME is deprecated.

Reading scale factors..
Available scale factor configuration set snb.interactive.0.1
Available scale factor configuration set snb.interactive.0.3
Available scale factor configuration set snb.interactive.1
Available scale factor configuration set snb.interactive.3
Available scale factor configuration set snb.interactive.10
Available scale factor configuration set snb.interactive.30
Available scale factor configuration set snb.interactive.100
Available scale factor configuration set snb.interactive.300
Available scale factor configuration set snb.interactive.1000
Available scale factor configuration set graphalytics.1
Available scale factor configuration set graphalytics.3
Available scale factor configuration set graphalytics.10
Available scale factor configuration set graphalytics.30
Available scale factor configuration set graphalytics.100
Available scale factor configuration set graphalytics.300
Available scale factor configuration set graphalytics.1000
Available scale factor configuration set graphalytics.3000
Available scale factor configuration set graphalytics.10000
Available scale factor configuration set graphalytics.30000
Number of scale factors read 19
Applied configuration of scale factor snb.interactive.0.1
null
Error during execution
java.lang.NullPointerException
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
	at ldbc.snb.datagen.util.ConfigParser.readConfig(ConfigParser.java:165)
	at ldbc.snb.datagen.util.ConfigParser.readConfig(ConfigParser.java:133)
	at ldbc.snb.datagen.LdbcDatagen.main(LdbcDatagen.java:341)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:160)
Caused by: java.lang.NullPointerException
	at ldbc.snb.datagen.util.ConfigParser.readConfig(ConfigParser.java:159)
	... 7 more

**Comment by szarnyasg** [comment]
I tried this on my Ubuntu 18.04. My `params.ini` looks as follows:

```ini
ldbc.snb.datagen.generator.scaleFactor:snb.interactive.0.1

ldbc.snb.datagen.serializer.dynamicActivitySerializer:ldbc.snb.datagen.serializer.snb.csv.dynamicserializer.activity.CsvBasicDynamicActivitySerializer
ldbc.snb.datagen.serializer.dynamicPersonSerializer:ldbc.snb.datagen.serializer.snb.csv.dynamicserializer.person.CsvBasicDynamicPersonSerializer
ldbc.snb.datagen.serializer.staticSerializer:ldbc.snb.datagen.serializer.snb.csv.staticserializer.CsvBasicStaticSerializer

ldbc.snb.datagen.parametergenerator.python:python2
```

I ran v0.3.2:

```bash
$ git checkout v0.3.2
$ ./run.sh
```

This completed successfully and put the generated parameters under `substitution_parameters`.

**Comment by francast95** [comment]
I am working with the following environment features:

ubuntu 19.10
python 2.7.16
maven 3.6.1
java openjdk 11.0.6 and java openjdk 8
hadoop 3.2.1
ldbc_snb_datagen-0.3.2

The followers environment variables:

export JAVA_HOME = /usr/lib/jvm/java-8-openjdk-amd64
export HADOOP_CLIENT_OPTS= -Xmx2G
export LDBC_SNB_DATAGEN_HOME=/home/fco/ldbc_snb_datagen-0.3.2
export HADOOP_HOME=/home/fco/hadoop-3.2.1

Road file:

DEFAULT_LDBC_SNB_DATAGEN_HOME=/home/fco/ldbc_snb_datagen-0.3.2
DEFAULT_HADOOP_HOME=/home/fco/hadoop-3.2.1

Params.ini:

ldbc.snb.datagen.generator.scaleFactor:snb.interactive.1

ldbc.snb.datagen.serializer.dynamicActivitySerializer:ldbc.snb.datagen.serializer.snb.csv.dynamicserializer.activity.CsvBasicDynamicActivitySerializer
ldbc.snb.datagen.serializer.dynamicPersonSerializer:ldbc.snb.datagen.serializer.snb.csv.dynamicserializer.person.CsvBasicDynamicPersonSerializer
ldbc.snb.datagen.serializer.staticSerializer:ldbc.snb.datagen.serializer.snb.csv.staticserializer.CsvBasicStaticSerializer

ldbc.snb.datagen.parametergenerator.python:python2
ldbc.snb.datagen.serializer.outputDir:./test_data/

And the outcome is the following:

************************************************
* Serializing static graph  *
************************************************
208 total seconds
Person generation time: 9
University correlated edge generation time: 6
Interest correlated edge generation time: 8
Random correlated edge generation time: 6
Edges merge time: 6
Person serialization time: 14
Person activity generation and serialization time: 91
Sorting update streams time: 64
Invariant schema serialization time: 0
Total Execution time: 208
Running Parameter Generation
Generating Interactive Parameters
Error during execution
Cannot run program "python2" (in directory "."): error=2, No existe el archivo o el directorio
Exception in thread "main" java.io.IOException: Cannot run program "python2" (in directory "."): error=2, No existe el archivo o el directorio
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at ldbc.snb.datagen.LdbcDatagen.runGenerateJob(LdbcDatagen.java:302)
	at ldbc.snb.datagen.LdbcDatagen.main(LdbcDatagen.java:347)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:323)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:236)
Caused by: java.io.IOException: error=2, No existe el archivo o el directorio
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 8 more

**Comment by szarnyasg** [comment]
The problem seems to be that `python2` is not on your path. If you just type `python2` in a terminal, does it work? If it does, you can use `which python2`. This returns `/usr/bin/python2` for me that can be used in the configuration:
```console
ldbc.snb.datagen.parametergenerator.python:/usr/bin/python2
```

**Comment by francast95** [comment]
sorry also I noticed that the output folder has the social_network folder and there are the static and dynamic folders where if they have the data, then the error that it throws from python is only at the end of the process.

**Comment by szarnyasg** [comment]
That's what I'd expect. The question is, do you need the substitution parameters?

**Comment by francast95** [comment]
I am working on resolve to BI query issue in Neo4j. will i need substitution parameters?

**Comment by francast95** [comment]
Ok problem solved with python2 installation

**Comment by szarnyasg** [comment]
Cool!
