### ISSUE TITLE
HadoopPersonSortAndSerializer.run fails with IOException

### ISSUE THREAD

**Issue by xiafangxc** [ldbc/ldbc_snb_datagen_spark#158]
```
* Serializing persons *
************************************************
20/04/26 13:41:40 INFO mapred.LocalJobRunner: OutputCommitter set in config null
20/04/26 13:41:40 INFO mapred.LocalJobRunner: OutputCommitter is org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter
20/04/26 13:41:40 INFO mapred.LocalJobRunner: Waiting for map tasks
20/04/26 13:41:40 INFO mapred.LocalJobRunner: Starting task: attempt_local1860273915_0012_m_000000_0
20/04/26 13:41:40 INFO util.ProcfsBasedProcessTree: ProcfsBasedProcessTree currently is supported only on Linux.
20/04/26 13:41:41 INFO mapred.LocalJobRunner: 
20/04/26 13:41:42 INFO mapred.LocalJobRunner: map
20/04/26 13:41:42 INFO mapred.LocalJobRunner: Finishing task: attempt_local1860273915_0012_m_000000_0
20/04/26 13:41:42 INFO mapred.LocalJobRunner: map task executor complete.
20/04/26 13:41:42 INFO mapred.LocalJobRunner: Waiting for reduce tasks
20/04/26 13:41:42 INFO mapred.LocalJobRunner: Starting task: attempt_local1860273915_0012_r_000000_0
20/04/26 13:41:42 INFO util.ProcfsBasedProcessTree: ProcfsBasedProcessTree currently is supported only on Linux.
20/04/26 13:41:42 INFO mapred.LocalJobRunner: 1 / 1 copied.
20/04/26 13:41:42 INFO mapred.LocalJobRunner: 1 / 1 copied.
20/04/26 13:41:42 INFO mapred.LocalJobRunner: 1 / 1 copied.
20/04/26 13:41:42 INFO mapred.LocalJobRunner: reduce > reduce
20/04/26 13:41:42 INFO mapred.LocalJobRunner: Finishing task: attempt_local1860273915_0012_r_000000_0
20/04/26 13:41:42 INFO mapred.LocalJobRunner: reduce task executor complete.
20/04/26 13:41:43 INFO mapred.LocalJobRunner: OutputCommitter set in config null
20/04/26 13:41:43 INFO mapred.LocalJobRunner: OutputCommitter is org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter
20/04/26 13:41:43 INFO mapred.LocalJobRunner: Waiting for map tasks
20/04/26 13:41:43 INFO mapred.LocalJobRunner: Starting task: attempt_local518842489_0013_m_000000_0
20/04/26 13:41:43 INFO util.ProcfsBasedProcessTree: ProcfsBasedProcessTree currently is supported only on Linux.
20/04/26 13:41:43 INFO mapred.LocalJobRunner: 
20/04/26 13:41:43 INFO mapred.LocalJobRunner: map
20/04/26 13:41:43 INFO mapred.LocalJobRunner: Finishing task: attempt_local518842489_0013_m_000000_0
20/04/26 13:41:43 INFO mapred.LocalJobRunner: map task executor complete.
20/04/26 13:41:43 INFO mapred.LocalJobRunner: Waiting for reduce tasks
20/04/26 13:41:43 INFO mapred.LocalJobRunner: Starting task: attempt_local518842489_0013_r_000000_0
20/04/26 13:41:43 INFO util.ProcfsBasedProcessTree: ProcfsBasedProcessTree currently is supported only on Linux.
20/04/26 13:41:43 INFO mapred.LocalJobRunner: 1 / 1 copied.
20/04/26 13:41:43 INFO mapred.LocalJobRunner: 1 / 1 copied.
20/04/26 13:41:44 INFO mapred.LocalJobRunner: 1 / 1 copied.
20/04/26 13:41:44 INFO mapred.LocalJobRunner: reduce > reduce
20/04/26 13:41:44 INFO mapred.LocalJobRunner: Finishing task: attempt_local518842489_0013_r_000000_0
20/04/26 13:41:44 INFO mapred.LocalJobRunner: reduce task executor complete.
20/04/26 13:41:44 INFO mapred.LocalJobRunner: OutputCommitter set in config null
20/04/26 13:41:44 INFO mapred.LocalJobRunner: OutputCommitter is org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter
20/04/26 13:41:44 INFO mapred.LocalJobRunner: Waiting for map tasks
20/04/26 13:41:44 INFO mapred.LocalJobRunner: Starting task: attempt_local1398502739_0014_m_000000_0
20/04/26 13:41:44 INFO util.ProcfsBasedProcessTree: ProcfsBasedProcessTree currently is supported only on Linux.
20/04/26 13:41:44 INFO mapred.LocalJobRunner: 
20/04/26 13:41:44 INFO mapred.LocalJobRunner: map
20/04/26 13:41:44 INFO mapred.LocalJobRunner: Finishing task: attempt_local1398502739_0014_m_000000_0
20/04/26 13:41:44 INFO mapred.LocalJobRunner: map task executor complete.
20/04/26 13:41:44 INFO mapred.LocalJobRunner: Waiting for reduce tasks
20/04/26 13:41:44 INFO mapred.LocalJobRunner: Starting task: attempt_local1398502739_0014_r_000000_0
20/04/26 13:41:44 INFO util.ProcfsBasedProcessTree: ProcfsBasedProcessTree currently is supported only on Linux.
20/04/26 13:41:44 INFO mapred.LocalJobRunner: 1 / 1 copied.
20/04/26 13:41:44 INFO mapred.LocalJobRunner: 1 / 1 copied.
20/04/26 13:41:44 INFO mapred.LocalJobRunner: reduce task executor complete.
20/04/26 13:41:44 WARN mapred.LocalJobRunner: job_local1398502739_0014
java.lang.Exception: java.io.IOException: Mkdirs failed to create file:/C:/Users/cl05/Documents/ldbc_snb_datagen/hadoop/aux/_temporary/0/_temporary/attempt_local1398502739_0014_r_000000_0 (exists=false, cwd=file:/C:/Users/cl05/Documents/ldbc_snb_datagen)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:492)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:559)
Caused by: java.io.IOException: Mkdirs failed to create file:/C:/Users/cl05/Documents/ldbc_snb_datagen/hadoop/aux/_temporary/0/_temporary/attempt_local1398502739_0014_r_000000_0 (exists=false, cwd=file:/C:/Users/cl05/Documents/ldbc_snb_datagen)
	at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:458)
	at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:443)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1103)
	at org.apache.hadoop.io.SequenceFile$Writer.<init>(SequenceFile.java:1168)
	at org.apache.hadoop.io.SequenceFile.createWriter(SequenceFile.java:285)
	at org.apache.hadoop.io.SequenceFile.createWriter(SequenceFile.java:542)
	at org.apache.hadoop.mapreduce.lib.output.SequenceFileOutputFormat.getSequenceWriter(SequenceFileOutputFormat.java:64)
	at org.apache.hadoop.mapreduce.lib.output.SequenceFileOutputFormat.getRecordWriter(SequenceFileOutputFormat.java:75)
	at org.apache.hadoop.mapred.ReduceTask$NewTrackingRecordWriter.<init>(ReduceTask.java:542)
	at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:615)
	at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:390)
	at org.apache.hadoop.mapred.LocalJobRunner$Job$ReduceTaskRunnable.run(LocalJobRunner.java:347)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Error during execution
null
Exception in thread "main" java.lang.Exception
	at ldbc.snb.datagen.hadoop.serializer.HadoopPersonSortAndSerializer.run(HadoopPersonSortAndSerializer.java:170)
	at ldbc.snb.datagen.LdbcDatagen.runGenerateJob(LdbcDatagen.java:159)
	at ldbc.snb.datagen.LdbcDatagen.main(LdbcDatagen.java:347)
```
_____________________________________________________
After that, I tried Debug pattern; I found it threw an Exception when execute
 `Job job = Job.getInstance(conf, "Person Serializer");` 
`Method threw 'java.lang.IllegalStateException' exception. Cannot evaluate org.apache.hadoop.mapreduce.Job.toString()`
![screenshot_20200426102308](https://user-images.githubusercontent.com/54089515/80295761-0ec0e700-87a8-11ea-8a37-0a75ea28c003.png)

I need help. Thank you!

**Comment by xiafangxc** [comment]
`* Serializing persons *
************************************************
20/04/26 13:41:40 INFO mapred.LocalJobRunner: OutputCommitter set in config null
20/04/26 13:41:40 INFO mapred.LocalJobRunner: OutputCommitter is org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter
20/04/26 13:41:40 INFO mapred.LocalJobRunner: Waiting for map tasks
20/04/26 13:41:40 INFO mapred.LocalJobRunner: Starting task: attempt_local1860273915_0012_m_000000_0
20/04/26 13:41:40 INFO util.ProcfsBasedProcessTree: ProcfsBasedProcessTree currently is supported only on Linux.
20/04/26 13:41:41 INFO mapred.LocalJobRunner: 
20/04/26 13:41:42 INFO mapred.LocalJobRunner: map
20/04/26 13:41:42 INFO mapred.LocalJobRunner: Finishing task: attempt_local1860273915_0012_m_000000_0
20/04/26 13:41:42 INFO mapred.LocalJobRunner: map task executor complete.
20/04/26 13:41:42 INFO mapred.LocalJobRunner: Waiting for reduce tasks
20/04/26 13:41:42 INFO mapred.LocalJobRunner: Starting task: attempt_local1860273915_0012_r_000000_0
20/04/26 13:41:42 INFO util.ProcfsBasedProcessTree: ProcfsBasedProcessTree currently is supported only on Linux.
20/04/26 13:41:42 INFO mapred.LocalJobRunner: 1 / 1 copied.
20/04/26 13:41:42 INFO mapred.LocalJobRunner: 1 / 1 copied.
20/04/26 13:41:42 INFO mapred.LocalJobRunner: 1 / 1 copied.
20/04/26 13:41:42 INFO mapred.LocalJobRunner: reduce > reduce
20/04/26 13:41:42 INFO mapred.LocalJobRunner: Finishing task: attempt_local1860273915_0012_r_000000_0
20/04/26 13:41:42 INFO mapred.LocalJobRunner: reduce task executor complete.
20/04/26 13:41:43 INFO mapred.LocalJobRunner: OutputCommitter set in config null
20/04/26 13:41:43 INFO mapred.LocalJobRunner: OutputCommitter is org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter
20/04/26 13:41:43 INFO mapred.LocalJobRunner: Waiting for map tasks
20/04/26 13:41:43 INFO mapred.LocalJobRunner: Starting task: attempt_local518842489_0013_m_000000_0
20/04/26 13:41:43 INFO util.ProcfsBasedProcessTree: ProcfsBasedProcessTree currently is supported only on Linux.
20/04/26 13:41:43 INFO mapred.LocalJobRunner: 
20/04/26 13:41:43 INFO mapred.LocalJobRunner: map
20/04/26 13:41:43 INFO mapred.LocalJobRunner: Finishing task: attempt_local518842489_0013_m_000000_0
20/04/26 13:41:43 INFO mapred.LocalJobRunner: map task executor complete.
20/04/26 13:41:43 INFO mapred.LocalJobRunner: Waiting for reduce tasks
20/04/26 13:41:43 INFO mapred.LocalJobRunner: Starting task: attempt_local518842489_0013_r_000000_0
20/04/26 13:41:43 INFO util.ProcfsBasedProcessTree: ProcfsBasedProcessTree currently is supported only on Linux.
20/04/26 13:41:43 INFO mapred.LocalJobRunner: 1 / 1 copied.
20/04/26 13:41:43 INFO mapred.LocalJobRunner: 1 / 1 copied.
20/04/26 13:41:44 INFO mapred.LocalJobRunner: 1 / 1 copied.
20/04/26 13:41:44 INFO mapred.LocalJobRunner: reduce > reduce
20/04/26 13:41:44 INFO mapred.LocalJobRunner: Finishing task: attempt_local518842489_0013_r_000000_0
20/04/26 13:41:44 INFO mapred.LocalJobRunner: reduce task executor complete.
20/04/26 13:41:44 INFO mapred.LocalJobRunner: OutputCommitter set in config null
20/04/26 13:41:44 INFO mapred.LocalJobRunner: OutputCommitter is org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter
20/04/26 13:41:44 INFO mapred.LocalJobRunner: Waiting for map tasks
20/04/26 13:41:44 INFO mapred.LocalJobRunner: Starting task: attempt_local1398502739_0014_m_000000_0
20/04/26 13:41:44 INFO util.ProcfsBasedProcessTree: ProcfsBasedProcessTree currently is supported only on Linux.
20/04/26 13:41:44 INFO mapred.LocalJobRunner: 
20/04/26 13:41:44 INFO mapred.LocalJobRunner: map
20/04/26 13:41:44 INFO mapred.LocalJobRunner: Finishing task: attempt_local1398502739_0014_m_000000_0
20/04/26 13:41:44 INFO mapred.LocalJobRunner: map task executor complete.
20/04/26 13:41:44 INFO mapred.LocalJobRunner: Waiting for reduce tasks
20/04/26 13:41:44 INFO mapred.LocalJobRunner: Starting task: attempt_local1398502739_0014_r_000000_0
20/04/26 13:41:44 INFO util.ProcfsBasedProcessTree: ProcfsBasedProcessTree currently is supported only on Linux.
20/04/26 13:41:44 INFO mapred.LocalJobRunner: 1 / 1 copied.
20/04/26 13:41:44 INFO mapred.LocalJobRunner: 1 / 1 copied.
20/04/26 13:41:44 INFO mapred.LocalJobRunner: reduce task executor complete.
20/04/26 13:41:44 WARN mapred.LocalJobRunner: job_local1398502739_0014
java.lang.Exception: java.io.IOException: Mkdirs failed to create file:/C:/Users/cl05/Documents/ldbc_snb_datagen/hadoop/aux/_temporary/0/_temporary/attempt_local1398502739_0014_r_000000_0 (exists=false, cwd=file:/C:/Users/cl05/Documents/ldbc_snb_datagen)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:492)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:559)
Caused by: java.io.IOException: Mkdirs failed to create file:/C:/Users/cl05/Documents/ldbc_snb_datagen/hadoop/aux/_temporary/0/_temporary/attempt_local1398502739_0014_r_000000_0 (exists=false, cwd=file:/C:/Users/cl05/Documents/ldbc_snb_datagen)
	at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:458)
	at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:443)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1103)
	at org.apache.hadoop.io.SequenceFile$Writer.<init>(SequenceFile.java:1168)
	at org.apache.hadoop.io.SequenceFile.createWriter(SequenceFile.java:285)
	at org.apache.hadoop.io.SequenceFile.createWriter(SequenceFile.java:542)
	at org.apache.hadoop.mapreduce.lib.output.SequenceFileOutputFormat.getSequenceWriter(SequenceFileOutputFormat.java:64)
	at org.apache.hadoop.mapreduce.lib.output.SequenceFileOutputFormat.getRecordWriter(SequenceFileOutputFormat.java:75)
	at org.apache.hadoop.mapred.ReduceTask$NewTrackingRecordWriter.<init>(ReduceTask.java:542)
	at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:615)
	at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:390)
	at org.apache.hadoop.mapred.LocalJobRunner$Job$ReduceTaskRunnable.run(LocalJobRunner.java:347)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Error during execution
null
Exception in thread "main" java.lang.Exception
	at ldbc.snb.datagen.hadoop.serializer.HadoopPersonSortAndSerializer.run(HadoopPersonSortAndSerializer.java:170)
	at ldbc.snb.datagen.LdbcDatagen.runGenerateJob(LdbcDatagen.java:159)
	at ldbc.snb.datagen.LdbcDatagen.main(LdbcDatagen.java:347)`

**Comment by xiafangxc** [comment]
Can I run it on windows?

**Comment by szarnyasg** [comment]
@xiafangxc Windows is currently not supported. Can you use Docker? That should work fine and is our recommended approach for generating small & medium data sets.

**Comment by xiafangxc** [comment]
@szarnyasg OK . I'll try it later. Thank you~
