### ISSUE TITLE
ArrayIndexOutOfBoundsException thrown during datagen

### ISSUE THREAD

**Issue by dutor** [ldbc/ldbc_snb_datagen_spark#188]
Here is the stacktrace 
```
2020-05-19 10:04:54,425 WARN impl.MetricsSystemImpl: JobTracker metrics system already initialized!
2020-05-19 10:04:54,433 WARN mapreduce.JobResourceUploader: Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
2020-05-19 10:14:37,526 WARN impl.MetricsSystemImpl: JobTracker metrics system already initialized!
2020-05-19 10:24:55,995 WARN impl.MetricsSystemImpl: JobTracker metrics system already initialized!
2020-05-19 10:24:56,003 WARN mapreduce.JobResourceUploader: Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
2020-05-19 10:33:50,858 WARN impl.MetricsSystemImpl: JobTracker metrics system already initialized!
2020-05-19 10:43:36,576 WARN impl.MetricsSystemImpl: JobTracker metrics system already initialized!
2020-05-19 10:43:36,585 WARN mapreduce.JobResourceUploader: Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
2020-05-19 10:52:01,156 WARN impl.MetricsSystemImpl: JobTracker metrics system already initialized!
2020-05-19 10:54:52,259 WARN mapred.LocalJobRunner: job_local830089419_0014
java.lang.Exception: java.lang.ArrayIndexOutOfBoundsException: 0
        at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:492)
        at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:559)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
        at ldbc.snb.datagen.hadoop.writer.HdfsWriter.write(HdfsWriter.java:80)
        at ldbc.snb.datagen.hadoop.writer.HdfsCsvWriter.writeEntry(HdfsCsvWriter.java:76)
        at ldbc.snb.datagen.serializer.snb.csv.dynamicserializer.person.CsvBasicDynamicPersonSerializer.serialize(CsvBasicDynamicPersonSerializer.java:139)
        at ldbc.snb.datagen.serializer.DynamicPersonSerializer.export(DynamicPersonSerializer.java:62)
        at ldbc.snb.datagen.hadoop.serializer.HadoopPersonSortAndSerializer$HadoopDynamicPersonSerializerReducer.reduce(HadoopPersonSortAndSerializer.java:123)
        at ldbc.snb.datagen.hadoop.serializer.HadoopPersonSortAndSerializer$HadoopDynamicPersonSerializerReducer.reduce(HadoopPersonSortAndSerializer.java:74)
        at org.apache.hadoop.mapreduce.Reducer.run(Reducer.java:171)
        at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:628)
        at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:390)
        at org.apache.hadoop.mapred.LocalJobRunner$Job$ReduceTaskRunnable.run(LocalJobRunner.java:347)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "main" java.lang.IllegalStateException: HadoopPersonSerializer failed
        at ldbc.snb.datagen.hadoop.serializer.HadoopPersonSortAndSerializer.run(HadoopPersonSortAndSerializer.java:220)
        at ldbc.snb.datagen.hadoop.LdbcDatagen.serializePersons(LdbcDatagen.java:106)
        at ldbc.snb.datagen.hadoop.LdbcDatagen.runGenerateJob(LdbcDatagen.java:215)
        at ldbc.snb.datagen.hadoop.LdbcDatagen.main(LdbcDatagen.java:451)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:323)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:236)
```

The _params.ini_ settings are:
```
generator.scaleFactor:1000
generator.numThreads:1
hadoop.numThreads:1
generator.mode:interactive
serializer.format:CsvBasic
```

The datagen is based on the _dev_ branch. If I set the scale factor to 100 or less, there is no such exception.

**Comment by dutor** [comment]
The
