### ISSUE TITLE
Turtle serializer

### ISSUE THREAD

**Issue by rubensworks** [ldbc/ldbc_snb_datagen_spark#228]
I seem to be unable to serialize to Turtle when setting the format using `serializer.format:Turtle`.

```
java.lang.IllegalStateException: Unexpected activity serializer: Turtle
	at ldbc.snb.datagen.util.LdbcConfiguration.getDynamicActivitySerializer(LdbcConfiguration.java:149)
	at ldbc.snb.datagen.spark.generators.SparkActivitySerializer$$anonfun$apply$1.apply(SparkActivitySerializer.scala:42)
	at ldbc.snb.datagen.spark.generators.SparkActivitySerializer$$anonfun$apply$1.apply(SparkActivitySerializer.scala:33)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:980)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:980)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I've skimmed through the issues, and saw this: https://github.com/ldbc/ldbc_snb_datagen/pull/161
Does this mean that this generator will not be supporting Turtle any more going forward?
If so, what alternative methods would you suggest to serialize to Turtle?

**Comment by szarnyasg** [comment]
Hi @rubensworks,

If your data sets sizes aren't huge, try the `stable` branch with Hadoop. That still has the Turtle serializer.

We're overhauling the code on the `dev` branch. Adding and RDF/Turtle serializer is on the list (#227) but has a low priority. So I cannot promise anything.

Gabor

**Comment by rubensworks** [comment]
Thanks for the reply!
I'll try to use the `stable` branch for now then.
