### ISSUE TITLE
Data generation fails with No space left on device error for SF=300

### ISSUE THREAD

**Issue by all-seeing-code** [ldbc/ldbc_snb_datagen_spark#254]
How much disk space is required for SF=300 or SF=1000? 

According to the report, it should be <300Gb. 

>For example, SF1 takes roughly 1 GiB in CSV format, SF3 weighs roughly 3 GiB and so on andso forth. It is important to note that for a given scale factor, data sets generated using different serializers containexaclty the same data, the only difference is in how they are represented.3The proposed SFs are the following:1, 3, 10, 30, 100, 300, 1000. Additionally, three small SFs, 0.003 (for quick tests of data loader components),0.1, and 0.3 are provided to help initial validation efforts.

`params.ini`:
```
ldbc.snb.datagen.generator.scaleFactor:snb.interactive.300

ldbc.snb.datagen.serializer.dynamicActivitySerializer:ldbc.snb.datagen.serializer.snb.csv.dynamicserializer.activity.CsvBasicDynamicActivitySerializer
ldbc.snb.datagen.serializer.dynamicPersonSerializer:ldbc.snb.datagen.serializer.snb.csv.dynamicserializer.person.CsvBasicDynamicPersonSerializer
ldbc.snb.datagen.serializer.staticSerializer:ldbc.snb.datagen.serializer.snb.csv.staticserializer.CsvBasicStaticSerializer

# To generate RFC 3339-compliant timestamps (https://tools.ietf.org/html/rfc3339), uncomment the following line:
ldbc.snb.datagen.util.formatter.StringDateFormatter.dateTimeFormat:yyyy-MM-dd'T'HH:mm:ss.SSS+00:00
```
Diskspace:
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       1.8T  343G  1.4T  20% /mnt/disk
```

Logs:
```
2020-12-08 19:49:09,498 WARN mapred.LocalJobRunner: job_local2096015576_0017
java.lang.Exception: org.apache.hadoop.fs.FSError: java.io.IOException: No space left on device
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:492)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:559)
Caused by: org.apache.hadoop.fs.FSError: java.io.IOException: No space left on device
	at org.apache.hadoop.fs.RawLocalFileSystem$LocalFSFileOutputStream.write(RawLocalFileSystem.java:275)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:182)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:72)
	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:101)
	at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSOutputSummer.close(ChecksumFileSystem.java:416)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:72)
	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:101)
	at org.apache.hadoop.io.SequenceFile$Writer.close(SequenceFile.java:1390)
	at org.apache.hadoop.mapreduce.lib.output.SequenceFileOutputFormat$1.close(SequenceFileOutputFormat.java:87)
	at org.apache.hadoop.mapred.ReduceTask$NewTrackingRecordWriter.close(ReduceTask.java:551)
	at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:630)
	at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:390)
	at org.apache.hadoop.mapred.LocalJobRunner$Job$ReduceTaskRunnable.run(LocalJobRunner.java:347)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: No space left on device
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
	at org.apache.hadoop.fs.RawLocalFileSystem$LocalFSFileOutputStream.write(RawLocalFileSystem.java:273)
	... 19 more
2020-12-08 19:49:10,031 INFO mapreduce.Job: Job job_local2096015576_0017 failed with state FAILED due to: NA
2020-12-08 19:49:10,039 INFO mapreduce.Job: Counters: 30
	File System Counters
		FILE: Number of bytes read=40273450545611
		FILE: Number of bytes written=37215128319939
		FILE: Number of read operations=0
		FILE: Number of large read operations=0
		FILE: Number of write operations=0
	Map-Reduce Framework
		Map input records=1254000
		Map output records=1254000
		Map output bytes=7633733801
		Map output materialized bytes=7638742848
		Input split bytes=29412
		Combine input records=0
		Combine output records=0
		Reduce input groups=4
		Reduce shuffle bytes=7638742848
		Reduce input records=40000
		Reduce output records=0
		Spilled Records=1254000
		Shuffled Maps =228
		Failed Shuffles=0
		Merged Map outputs=228
		GC time elapsed (ms)=5620
		Total committed heap usage (bytes)=482889170944
	Shuffle Errors
		BAD_ID=0
		CONNECTION=0
		IO_ERROR=0
		WRONG_LENGTH=0
		WRONG_MAP=0
		WRONG_REDUCE=0
	File Input Format Counters 
		Bytes Read=7702873605
	File Output Format Counters 
		Bytes Written=8
Error during execution
null
Exception in thread "main" java.lang.Exception
	at ldbc.snb.datagen.hadoop.generator.HadoopPersonActivityGenerator.run(HadoopPersonActivityGenerator.java:207)
	at ldbc.snb.datagen.LdbcDatagen.runGenerateJob(LdbcDatagen.java:170)
	at ldbc.snb.datagen.LdbcDatagen.main(LdbcDatagen.java:347)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:323)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:236)
```

**Comment by szarnyasg** [comment]
Hi @anurags92,

> How much disk space is required for SF=300 or SF=1000?
SF300 is roughly 300GiB, SF1000 is 1TiB plus a bit for the temp files. 1.4TB of storage should be enough for both.

Do you use Docker or a local Spark installation?

In both cases, it is possible that your temp folder runs out of space. Cloud VMs at certain providers come with small-sized `/` partitions and the `/tmp` directory can fill up quickly.

If you use Docker check out the troubleshooting section in the README: https://github.com/ldbc/ldbc_snb_datagen/#troubleshooting

**Comment by all-seeing-code** [comment]
Wow! That was quick. I am using a local Spark installation. Is there a way to side-step this? I have a fairly good system with 32gig RAM and 1TB SSD.

**Comment by szarnyasg** [comment]
You can set the temp directory by changing `spark.local.dir` (https://spark.apache.org/docs/2.4.0/configuration.html).
That said, 32GB RAM might not be sufficient for larger data sets. I can provide pre-generated CsvBasic data sets -- you'll have to change the date fields to match RFC3339 but that's doable. If you're interested, ping me via email (my address is on my profile).

**Comment by all-seeing-code** [comment]
I have dropped an email, closing this issue. Thanks!
