### ISSUE TITLE
java.lang.Exception

### ISSUE THREAD

**Issue by vandykai** [ldbc/ldbc_snb_datagen_spark#31]
```
17/06/03 01:12:15 INFO mapreduce.Job:  map 0% reduce 0%
17/06/03 01:12:28 INFO mapreduce.Job:  map 67% reduce 0%
17/06/03 01:12:35 INFO mapreduce.Job: Task Id : attempt_1496421666783_0002_m_000000_0, Status : FAILED
Error: GC overhead limit exceeded
17/06/03 01:12:36 INFO mapreduce.Job:  map 0% reduce 0%
17/06/03 01:12:46 INFO mapreduce.Job:  map 67% reduce 0%
17/06/03 01:12:53 INFO mapreduce.Job: Task Id : attempt_1496421666783_0002_m_000000_1, Status : FAILED
Error: GC overhead limit exceeded
17/06/03 01:12:54 INFO mapreduce.Job:  map 0% reduce 0%
17/06/03 01:13:04 INFO mapreduce.Job:  map 67% reduce 0%
17/06/03 01:20:10 INFO mapreduce.Job: Task Id : attempt_1496421666783_0002_m_000000_2, Status : FAILED
Error: Java heap space
17/06/03 01:20:11 INFO mapreduce.Job:  map 0% reduce 0%
17/06/03 01:20:22 INFO mapreduce.Job:  map 67% reduce 0%
17/06/03 01:20:30 INFO mapreduce.Job:  map 100% reduce 0%
17/06/03 01:20:31 INFO mapreduce.Job:  map 100% reduce 100%
17/06/03 01:20:32 INFO mapreduce.Job: Job job_1496421666783_0002 failed with state FAILED due to: Task failed task_1496421666783_0002_m_000000
Job failed as tasks failed. failedMaps:1 failedReduces:0

17/06/03 01:20:32 INFO mapreduce.Job: Counters: 8
	Job Counters 
		Failed map tasks=4
		Launched map tasks=4
		Other local map tasks=4
		Total time spent by all maps in occupied slots (ms)=486829
		Total time spent by all reduces in occupied slots (ms)=0
		Total time spent by all map tasks (ms)=486829
		Total vcore-seconds taken by all map tasks=486829
		Total megabyte-seconds taken by all map tasks=498512896
Error during execution
null
java.lang.Exception
	at ldbc.snb.datagen.hadoop.HadoopPersonGenerator.run(HadoopPersonGenerator.java:138)
	at ldbc.snb.datagen.generator.LDBCDatagen.runGenerateJob(LDBCDatagen.java:97)
	at ldbc.snb.datagen.generator.LDBCDatagen.main(LDBCDatagen.java:372)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
```

When I run run.sh, I got this message. What I only changed is HADOOP_HOME and LDBC_SNB_DATAGEN_HOME.

**Comment by vandykai** [comment]
Add this in mapred-site.xml
```
<property>
	<name>mapred.child.java.opts</name>
	 <value>-Xmx4096m</value>
</property>
```

you can also add this in yarn-site.xml
```
    <property>
        <name>yarn.nodemanager.vmem-check-enabled</name>
        <value>false</value>
        <description>Whether virtual memory limits will be enforced for containers</description>
    </property>
    <property>
        <name>yarn.nodemanager.vmem-pmem-ratio</name>
        <value>4</value>
        <description>Ratio between virtual memory to physical memory when setting memory limits for containers</description>
    </property>
```

**Comment by maverick-zhn** [comment]
I am getting a similar error when generating graphalytics.scale.10.

Any suggestion?

Thanks in advance.

```
--
File System Counters
  |   | +                FILE: Number of bytes read=140378909105
  |   | +                FILE: Number of bytes written=162045913385
  |   | +                FILE: Number of read operations=0
  |   | +                FILE: Number of large read operations=0
  |   | +                FILE: Number of write operations=0
  |   | +        Map-Reduce Framework
  |   | +                Map input records=682617
  |   | +                Map output records=682617
  |   | +                Map output bytes=1027021045
  |   | +                Map output materialized bytes=1029718460
  |   | +                Input split bytes=4671
  |   | +                Combine input records=0
  |   | +                Spilled Records=682617
  |   | +                Failed Shuffles=0
  |   | +                Merged Map outputs=0
  |   | +                GC time elapsed (ms)=5270
  |   | +                CPU time spent (ms)=0
  |   | +                Physical memory (bytes) snapshot=0
  |   | +                Virtual memory (bytes) snapshot=0
  |   | +                Total committed heap usage (bytes)=16438001664
  |   | +        File Input Format Counters
  |   | +                Bytes Read=1046746322
  |   | +Error during execution
  |   | +null
  |   | +java.lang.Exception
  |   | +        at ldbc.snb.datagen.hadoop.HadoopMergeFriendshipFiles.run(HadoopMergeFriendshipFiles.java:117)
  |   | +        at ldbc.snb.datagen.generator.LDBCDatagen.runGenerateJob(LDBCDatagen.java:153)
  |   | +        at ldbc.snb.datagen.generator.LDBCDatagen.main(LDBCDatagen.java:375)
  |   | +        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  |   | +        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  |   | +        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  |   | +        at java.lang.reflect.Method.invoke(Method.java:498)
  |   | +        at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
  |   | +        at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
  |   | +17/07/07 21:19:58 INFO mapred.LocalJobRunner: reduce > copy task(attempt_local1945303119_0011_m_000024_0 succeeded at 31782.28 MB/s) Aggregated copy rate(9 of 33 at 285969.25 MB/s)
```

**Comment by ArnauPrat** [comment]
Do this happens with smaller scale factors? From my experience, this looks like the typical Hadoop job crash due to a lack of memory. Have you looked at Hadoop logs?

**Comment by maverick-zhn** [comment]
Thanks for your fast reply. It worked with scale 1. I augmented the memory to 6GB. However, it fails for graphalytics-scale-10 and so on. 

What is the recommended configuration to generate the larger scale factors synthetic datasets? 

Yes, it is indeed a lack-of-memory problem.

Thank you in advance.

**Comment by ArnauPrat** [comment]
Are you running hadoop on a cluster or a big machine, or in your laptop? Bear in mind that large scale factors are meant to be generated with beefy machines or clusters. How many threads are you executing the generator with?
